version: '2'
services:
  shopfront:
    image: elias1977/djshopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image:  elias1977/djproductcatalogue
    ports:
     - "8020:8020"
  stockmanager:
    image:  elias1977/djstockmanager
    ports:
     - "8030:8030"
